# github action to deploy portionsandpassion api to aws ec2

name: Deploy PortionsAndPassion Node API

on:
  pull_request:
    branches: [ "main" ]

  push:
    branches: [ "main" ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY  }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          
            #Now we have got the access of EC2 and we will start the deploy .
            DIR="/home/ec2-user/server"
            pm2 delete all
            cd /home/ec2-user
            
            if [ ! -d $DIR ]
            then
              mkdir server &&
              git clone https://github.com/appohfaiths/node-express-ec2-api.git server &&
              cd server &&
              npm i
            else
              cd server
            fi
            
            git checkout main &&
            git fetch --all &&
            git reset --hard origin/main &&
            git pull origin main &&
            pm2 start index.js
          '
            
     