# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Portions and Passion Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Create dist directory and copy .env if it exists
      run: |
        # Create the 'dist' directory if it doesn't exist
        mkdir -p dist

        # Check if the .env file exists before copying
        if [ -f .env ]; then
          cp .env dist/
        fi
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: |
        touch dist/.env
        echo "${{ secrets.PROD_ENV_FILE }}" >> dist/.env
    - name: Install pm2
      run: npm install -g pm2
    - name: Buld and start application
      run: |
        npm run build --if-present

        # Change to the directory where your Node.js application is located
        cd /home/ubuntu/actions-runner-backend/_work/node-express-ec2-api/node-express-ec2-api

        pm2 delete all

        # Start your Node.js app using pm2
        pm2 start npm -- start

        # Print the contents of the PM2 error log
        pm2 log
    - name: Display pm2 Process Lists
      run: pm2 list